### ISSUE TITLE
请问这个域名的适用范围

### ISSUE THREAD

**Issue by eyaeya** [ifr0zen/DoH-for-iMessage-FaceTime#1]
能否应对Apple其他被屏蔽服务？如：
1. macOS 与 iOS 互通的桌面小组件。
2. macOS / iPadOS / iOS 之间的跨设备复制粘贴。
3. iOS 与其他设备的 Handoff。

**Comment by ifr0zen** [comment]
昨天向苹果咨询过这个域名有哪些作用还没有得到答复，但是经过实测发现将域名列入规则代理后Apple 设备上的连续互通功能就会恢复

**Comment by ifr0zen** [comment]
域名适用范围已更新
