### ISSUE TITLE
请问方法中描述文件的作用是什么？

### ISSUE THREAD

**Issue by clocktowerc** [ifr0zen/DoH-for-iMessage-FaceTime#2]
如果将IM相关域名添加到代理规则走国外服务器，DNS解析应该是由代理服务器完成的，那描述文件的意义是什么？

**Comment by ifr0zen** [comment]
dns的工作原理详情自行搜索，大致是通过UDP协议明文传输，所以这中间会有dns欺骗或劫持等，doh做的是加密工作，早期在同一网络下移除sim卡后可以直接通过Apple ID登录，猜测电信针对SIM卡登录做了劫持，所以加了doh，可以尝试移除描述文件不影响使用的话就可以
