### ISSUE TITLE
请问vpn软件必须要一直打开吗  

### ISSUE THREAD

**Issue by wc953** [ifr0zen/DoH-for-iMessage-FaceTime#3]
单纯的改DNS无法解决问题吗  VPN如果常开的话节点不稳定可能会影响日常上网使用吧

**Comment by ifr0zen** [comment]
1.每个人的设备不同，第一个问题可以自行尝试调整，本方法是为了适配大多数使用场景。
2.VPN常开其实不太影响日常上网，已经将iM需要的网络请求列入代理，平时的网络活动是不会走代理的，会走直连，如果你的节点不稳定只会影响iM和设备之间的互联互通功能

**Comment by FlyRocker** [comment]
大佬能否给一个Quantumult X的方案

**Comment by ifr0zen** [comment]
![IMG_3942](https://github.com/ifr0zen/DoH-for-iMessage-FaceTime/assets/17274321/0578912a-45f1-4e8d-9eb5-e9430bd06e12)
![IMG_3943](https://github.com/ifr0zen/DoH-for-iMessage-FaceTime/assets/17274321/3edc4fcb-a56e-480a-9e1c-88e9284ba1f7)
![IMG_3944](https://github.com/ifr0zen/DoH-for-iMessage-FaceTime/assets/17274321/b2106141-0098-4e4b-9455-35a46088e14e)

**Comment by FlyRocker** [comment]
具体怎么填写参数？
